package camilamodas;

import dao.*;
import dao.entity.*;
import java.awt.event.KeyEvent;
import java.awt.event.WindowEvent;
import java.util.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

public class FrmPedido extends JFrame {
    Vendedor vendedor;
    Cliente cliente;
    List<Produto> produtos;
    
    float total = 0;
    
    JFrame parent;
    
    public FrmVenda(Vendedor vendedor, Cliente cliente, JFrame parent) {
        initComponents();
        super.setLocationRelativeTo(null);
        this.parent = parent;
        parent.setEnabled(false);
        
        this.cliente = cliente;
        this.vendedor = vendedor;
        
        lblVendedor.setText(lblVendedor.getText() + vendedor.getNome());
        lblCliente.setText(lblCliente.getText() + cliente.getNome());
        
        try {
            produtos = DAOFactory.getProdutoDAO().getAllProdutos();
            
            for (Produto produto : produtos) {
                String descricao = produto.getDescricao();
                
                switch (produto.getTamanho()) {
                    case 'P':
                        descricao += " (Pequeno)";
                        break;
                    case 'M':
                        descricao += " (Pequeno)";
                        break;
                    case 'G':
                        descricao += " (Grande)";
                        break;
                    case 'X':
                        descricao += " (Ex. Grande)";
                        break;
                }
                
                descricao += String.format(" R$ %.2f", produto.getValor());
                cmbProduto.addItem(descricao);
            }
        }
        catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        pnlContent = new javax.swing.JPanel();
        lblVendedor = new javax.swing.JLabel();
        lblCliente = new javax.swing.JLabel();
		lblIDProduto = new javax.swing.JLabel();
		lblNome = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cmbProduto = new javax.swing.JComboBox<>();
        lblTotal = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbItens = new javax.swing.JTable();
        cmbFormaPagamento = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        btnFinalizar = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        pnlContent.setBackground(new java.awt.Color(255, 255, 255));

        lblVendedor.setText("Vendedor: ");

        lblCliente.setText("Cliente: ");

        jLabel3.setText("Produto");

        lblTotal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTotal.setText("Total: R$ 0,00");

        btnAdd.setText("Adicionar");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        tbItens.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Produto", "EAN", "Quantidade", "Preço"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbItens.setColumnSelectionAllowed(true);
        tbItens.getTableHeader().setReorderingAllowed(false);
        tbItens.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tbItensKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tbItens);
        tbItens.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        if (tbItens.getColumnModel().getColumnCount() > 0) {
            tbItens.getColumnModel().getColumn(0).setResizable(false);
            tbItens.getColumnModel().getColumn(0).setPreferredWidth(150);
            tbItens.getColumnModel().getColumn(1).setResizable(false);
            tbItens.getColumnModel().getColumn(1).setPreferredWidth(30);
            tbItens.getColumnModel().getColumn(2).setResizable(false);
            tbItens.getColumnModel().getColumn(2).setPreferredWidth(10);
            tbItens.getColumnModel().getColumn(3).setResizable(false);
            tbItens.getColumnModel().getColumn(3).setPreferredWidth(10);
        }

        cmbFormaPagamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dinheiro", "Cheque", "Débito", "Crédito" }));

        jLabel4.setText("Forma de Paramento");

        btnFinalizar.setText("Finalizar");
        btnFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlContentLayout = new javax.swing.GroupLayout(pnlContent);
        pnlContent.setLayout(pnlContentLayout);
        pnlContentLayout.setHorizontalGroup(
            pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContentLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlContentLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbProduto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAdd))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 524, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlContentLayout.createSequentialGroup()
                        .addComponent(lblTotal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbFormaPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnFinalizar))
                    .addGroup(pnlContentLayout.createSequentialGroup()
                        .addComponent(lblVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlContentLayout.setVerticalGroup(
            pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContentLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVendedor)
                    .addComponent(lblCliente))
                .addGap(11, 11, 11)
                .addGroup(pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cmbProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdd))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cmbFormaPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)
                        .addComponent(btnFinalizar))
                    .addComponent(lblTotal))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        getContentPane().add(pnlContent, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarActionPerformed
        DefaultTableModel tableModel = (DefaultTableModel)tbItens.getModel();
        List<ItemVenda> itens = new ArrayList();

        if (tableModel.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this, "Insira algum item para ser vendido.");
            return;
        }

        //Pega os itens de venda da tabela
        for (int linha = 0; linha < tableModel.getRowCount(); linha++) {
            itens.add(new ItemVenda(
                    (String)tableModel.getValueAt(linha, 1),
                    (int)tableModel.getValueAt(linha, 2),
                    (float)tableModel.getValueAt(linha, 3)
                )
            );
        }

        try {
            DAOFactory.getVendaDAO().addVenda(
                new Venda(
                    cliente.getCpf(),
                    vendedor.getCpf(),
                    cmbFormaPagamento.getSelectedItem().toString()
                ),
                itens
            );

            JOptionPane.showMessageDialog(this, "Venda finalizada!");
            dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
        }
        catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Erro ao finalizar a venda.");
        }
    }//GEN-LAST:event_btnFinalizarActionPerformed

    private void tbItensKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbItensKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_DELETE) {
            DefaultTableModel tableModel = (DefaultTableModel)tbItens.getModel();
            int linha = tbItens.getSelectedRow();

            if (linha != -1) {
                total -= (float)tableModel.getValueAt(linha, 3);
                lblTotal.setText(String.format("Total: R$%.2f", total));

                tableModel.removeRow(linha);
            }

            //Resolve um erro de precisão
            if (tableModel.getRowCount() == 0)
            total = 0;
        }
    }//GEN-LAST:event_tbItensKeyPressed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        DefaultTableModel tableModel = (DefaultTableModel)tbItens.getModel();
        Produto produto = produtos.get(cmbProduto.getSelectedIndex());
        int linha = -1;

        //Procura a linha em que o produto está
        for (int i = 0; i < tableModel.getRowCount(); i++) {
            if ( ( (String)tableModel.getValueAt(i, 1) ).equals(produto.getEan()) ) {
                linha = i;
                break;
            }
        }

        if (linha == -1) {
            tableModel.addRow(new Object[] {
                produto.getDescricao(),
                produto.getEan(),
                1,
                produto.getValor()
            });
        }
        else {
            int qtde = (int)tableModel.getValueAt(linha, 2) + 1;

            tableModel.setValueAt(qtde, linha, 2);
            tableModel.setValueAt(qtde * produto.getValor(), linha, 3);
        }

        total += produto.getValor();
        lblTotal.setText(String.format("Total: R$%.2f", total));
    }//GEN-LAST:event_btnAddActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        parent.setEnabled(true);
    }//GEN-LAST:event_formWindowClosing

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnFinalizar;
    private javax.swing.JComboBox<String> cmbFormaPagamento;
    private javax.swing.JComboBox<String> cmbProduto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCliente;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblVendedor;
    private javax.swing.JPanel pnlContent;
    private javax.swing.JTable tbItens;
    // End of variables declaration//GEN-END:variables
}
